# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 14:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('z_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timestamp_ref', models.DecimalField(decimal_places=2, max_digits=17)),
                ('job_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('z_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timestamp_ref', models.DecimalField(decimal_places=2, max_digits=17)),
                ('job_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_\\s+]+$', 'Use alphanumeric characters and underscore only')], verbose_name='Sensor name')),
            ],
        ),
        migrations.AddField(
            model_name='frequency',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_data.Sensor', verbose_name='Sensor'),
        ),
        migrations.AddField(
            model_name='acceleration',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_data.Sensor', verbose_name='Sensor'),
        ),
    ]
