# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 22:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-\\s+]+$', 'Use alphanumeric characters and underscore and hyphen only')], verbose_name='Sensor name')),
            ],
        ),
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_data.Data')),
            ],
            bases=('sensor_data.data',),
        ),
        migrations.CreateModel(
            name='Amplitude',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_data.Data')),
            ],
            bases=('sensor_data.data',),
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_data.Data')),
            ],
            bases=('sensor_data.data',),
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_data.Data')),
            ],
            bases=('sensor_data.data',),
        ),
        migrations.AddField(
            model_name='data',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_data.Sensor', verbose_name='Sensor'),
        ),
    ]
