# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 13:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_\\s+]+$', 'Use alphanumeric characters and underscore only')], verbose_name='Sensor name'),
        ),
    ]
