# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceleration',
            name='x_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='y_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='z_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='x_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='y_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='z_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
