# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_auto_20160918_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='x_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='y_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='z_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
