# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0003_auto_20160923_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='job_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
